Add SIMD test to CI

diff --git a/.github/workflows/linux-arm-opengl.yml b/.github/workflows/linux-arm-opengl.yml
--- a/.github/workflows/linux-arm-opengl.yml
+++ b/.github/workflows/linux-arm-opengl.yml
@@ -4,6 +4,7 @@ on:
   push:
     branches:
     - main
+    - moarSIMD
   pull_request:
     branches:
     - main
@@ -66,3 +67,13 @@ jobs:
             cd ../../..
             echo " * Check Test 1"
             compare-im6 -metric mae Tests/Shader/reference.png Tests/Shader/Deployment/test.png difference.png
+            echo " * Clean"
+            rm -rf build
+            echo " * Compile Test 2 (SIMD)"
+            ./make -g opengl --kinc . --from Tests/SIMD --compile --noshaders
+            echo " * Copy Test 2"
+            cp build/Release/SIMD Tests/SIMD/Deployment/SIMD
+            echo " * Run Test 2"
+            cd Tests/SIMD/Deployment
+            ./SIMD && echo "SUCCESS" || echo "FAILED"
+            cd ../../..
